### ISSUE TITLE
As a user, I want to be able to see who follows and is following a user on their profile page

### ISSUE THREAD

**Issue by jason-gerard** [LujainKhalaf/SOEN341#113]
### Title

As a user, I want to be able to see who follows and is following a user on their profile page because I want to see if we have any mutual connections

### Describe the feature or problem you'd like to solve

A user on anyones profile page should be able to see a list of users who follow and are followed by profile user.

### Sub tasks
- Design and implement a modal to for the followers and following #112

### Acceptance test

1. Go to the website
2. Log in with the following credentials: 
    - username: user1@test.com
    - password: !Test1
3. Press the user's profile icon in the navigation bar
4. Press the profile option in the drop-down menu
5. User is redirected to their respective profile page
6. Press the "following" option in the profile page header to see who he is following
7. Press the "followers" option in the profile page header to see who follows him

### Expected results

- The user will be redirected to their profile
- The user will be able to see the number of his follower and the number of people he is following
- The user will be able to click on those two options
- The user will be redirected to the a page that contains the list of  his followers
- The user will be redirected to the a page that contains the list of  the people he follows
- The user will be able to click on all users icon to access their profile

**Comment by domsec** [comment]
Completed and merged with PR #163.
