### ISSUE TITLE
Design and implement the post comment ui for a feed post

### ISSUE THREAD

**Issue by jason-gerard** [LujainKhalaf/SOEN341#120]
## Goal

A single line input field with a submit button that will allow the user to enter their comment
When the button is clicked the comment should be submitted / posted to the backend

A scrolling list of comments, newest at the top. This should look similar to the profile page post modal comment section.
The screenshot shows a concatenated list, we will have it scrolling instead, but the rest of the ui elements should look the same/similar.

## Dev notes
- This action should be asynchronous and should not require a page reload
  - This can be done by making a POST request using javascript and injecting the new comment into the current list of comments on that post
- The api used in this ticket will be the same one used for #116

**User Interface**

![image](https://user-images.githubusercontent.com/19786843/108575350-edf1f100-72e7-11eb-9034-12c42071d88b.png)

- Display at most the 2 most recent comments for a given post
- "View all # comments"
    - Display when comments > 2
    - On click -> display the associated Modal #116
    - Do not display if the post originally had < 2 comments and the same user creates enough comments to result in the post having > 2 comments
    - If displayed, increase count by 1 for each newly added comment
- Every comment has the commenters username (clickable to redirect to their profile page) and comment text
- If a comment length > 120 characters, display a clickable `... more` link to expand the comment
- A comment posted in either post card or modal must be added to both the card and modal
- Emoji's, hashtags, replies, tagging other users are not supported in comments

**Validation**
- Same as #116

**Comment by domsec** [comment]
- "View all # Comments"
    - Only show when comments > 2
    - On click -> modal
