### ISSUE TITLE
As a user, I want to be able to view a users profile

### ISSUE THREAD

**Issue by jason-gerard** [LujainKhalaf/SOEN341#146]
## Title: 
As a user, I want to be able to view a users profile so that I can view who they follow, their latest posts, and details about them.

## Description: 
A user should be able to view their own and another users info on their profile page
A user should be able to view that users posts from their profile page
A user should be able to view who that user follows and who is following that user

## User stories:
- As a user, I want to be able to see who follows and is following a user on their profile page #113
- As a user, I want to be able to view the description of a post on the profile page #109

**Comment by domsec** [comment]
All related user stories and tasks are completed and merged.
