### ISSUE TITLE
Potential Issues/PR labels

### ISSUE THREAD

**Issue by domsec** [LujainKhalaf/SOEN341#21]
**Format:** _label name (color)_

**Add & Replace**
- Priority
    - priority-low (#0E8A16)
    - priority-medium (#FBCA04)
    - priority-high (#D73A4A)
    - priority-critical (#B60205)
- Type
    - bug (#D73A4A)
    - duplicate (#FABEF8)
    - invalid (#FABEF8)
    - feature-request (#87EEFF)
    - feature (#9BFF87)
    - question (#E8E8E8)
    - wont fix (#FABEF8) - replace `wontfix` label
    - documentation (#000000)
    - help wanted (#008672)
    - task (#7EC6FC)
    - good first issue (#7057FF)
    - discussion (#E8E8E8)
    - enhancement (#A2EEEF)
    - fixed (#0E8A16)
    - feedback needed (#5C3DE3)
    - more info needed (#5C3DE3)
- Other
    - repository (#000000)
    - wiki (#000000)
- Development
    - back end (#BFD4F2)
    - front end (#D4C5F9)
    - tech-debt (#E8E8E8)
    - dependencies (#0075CA)
    - localization (#C5DEF5)
    - configuration (#0075CA) - replace `setup` label
    - testing (#C5DEF5)
    - authentication (#C5DEF5)
- Project Management
    - iteration-plan (#E8E8E8)
    - iteration-eval (#E8E8E8)
    - epic (#670F9A)
    - user story (#015890)

**Remove**
- good first issue

**Comment by jason-gerard** [comment]
I'm good with this
