### ISSUE TITLE
Design and implement the signup page

### ISSUE THREAD

**Issue by jason-gerard** [LujainKhalaf/SOEN341#60]
### Goal
Implement a FE similar to https://www.instagram.com/accounts/emailsignup/

### Dev notes

**User Interface**

![image](https://user-images.githubusercontent.com/19786843/107081024-11814b80-67c0-11eb-9d34-69986c5bce4d.png)

- Display errors - in red - in a group above the form
- Add a red border to the input fields if there is an error associated to it
- Do not disable `Sign up` button if the form is not filled out

**Validation**

- Email
    - Required (`Enter an email address`)
    - Length: 50 characters maximum (`Email cannot be more than 50 characters long.`)
    - Unique (`Email <email> already exists.`)
    - Must be valid (`Enter a valid email address.`)
-  Full Name
    - Required (`Enter a full name.`)
    - Length: 50 characters maximum (`Full name cannot be more than 50 characters long.`)
- Username
    - Required (`Enter a username.`)
    - Alphanumeric only (`Username can only contain characters and numbers.`)
    - Unique (`Username <username> already exists.`)
    - Length: 3-15 characters (`Username must be 3 to 15 characters long.`)
- Password
    - Required (`Enter a password.`)
    - Length: 6-20 characters (`Password must be 6 to 20 characters long.`)

**Comment by domsec** [comment]
Items left to do

- [ ] Disable `Sign up` until form is filled out
- [ ] Display errors from back end
- [ ] Form security (cross site scripting)
- [ ] Form input limits (length)
