### ISSUE TITLE
Implement Flask-WTF library

### ISSUE THREAD

**Issue by domsec** [LujainKhalaf/SOEN341#74]
### Describe the feature or problem you'd like to solve

We do not have a simplified and quick way to handle all form validation, integration and CRSF protection.  

### Proposed solution

Use the Flask-WTF library to simplify all things form related (creation, validation, integration and CRSF protection).

Everything we would need is built in allowing us to save a bunch of time on trivial validation of fields.

### Additional context

Usage & Implementation Examples:
- https://hackersandslackers.com/flask-wtforms-forms/
- https://overiq.com/flask-101/form-handling-in-flask/

**Comment by mnashat** [comment]
I agree. Flask-WTF library should be good for this as suggested.
